/* Datos base de exclusivos: verificados con guías Switch/Switch 2 (feb 2026)
   y localizaciones RankedBoost FRLG. Deoxys se documenta aparte (forma Ataque /
   Defensa) porque PokéAPI lo sirve como un único nº 386. */

const FIRE_RED = [
  { id: 23, slug: "ekans", types: ["poison"] },
  { id: 24, slug: "arbok", types: ["poison"] },
  { id: 43, slug: "oddish", types: ["grass", "poison"] },
  { id: 44, slug: "gloom", types: ["grass", "poison"] },
  { id: 45, slug: "vileplume", types: ["grass", "poison"] },
  { id: 54, slug: "psyduck", types: ["water"] },
  { id: 55, slug: "golduck", types: ["water"] },
  { id: 58, slug: "growlithe", types: ["fire"] },
  { id: 59, slug: "arcanine", types: ["fire"] },
  { id: 90, slug: "shellder", types: ["water"] },
  { id: 91, slug: "cloyster", types: ["water", "ice"] },
  { id: 123, slug: "scyther", types: ["bug", "flying"] },
  { id: 125, slug: "electabuzz", types: ["electric"] },
  { id: 182, slug: "bellossom", types: ["grass"] },
  { id: 194, slug: "wooper", types: ["water", "ground"] },
  { id: 195, slug: "quagsire", types: ["water", "ground"] },
  { id: 198, slug: "murkrow", types: ["dark", "flying"] },
  { id: 211, slug: "qwilfish", types: ["water", "poison"] },
  { id: 212, slug: "scizor", types: ["bug", "steel"] },
  { id: 225, slug: "delibird", types: ["ice", "flying"] },
  { id: 227, slug: "skarmory", types: ["steel", "flying"] },
  { id: 239, slug: "elekid", types: ["electric"] },
];

const LEAF_GREEN = [
  { id: 27, slug: "sandshrew", types: ["ground"] },
  { id: 28, slug: "sandslash", types: ["ground"] },
  { id: 37, slug: "vulpix", types: ["fire"] },
  { id: 38, slug: "ninetales", types: ["fire"] },
  { id: 69, slug: "bellsprout", types: ["grass", "poison"] },
  { id: 70, slug: "weepinbell", types: ["grass", "poison"] },
  { id: 71, slug: "victreebel", types: ["grass", "poison"] },
  { id: 79, slug: "slowpoke", types: ["water", "psychic"] },
  { id: 80, slug: "slowbro", types: ["water", "psychic"] },
  { id: 120, slug: "staryu", types: ["water"] },
  { id: 121, slug: "starmie", types: ["water", "psychic"] },
  { id: 126, slug: "magmar", types: ["fire"] },
  { id: 127, slug: "pinsir", types: ["bug"] },
  { id: 183, slug: "marill", types: ["water", "fairy"] },
  { id: 184, slug: "azumarill", types: ["water", "fairy"] },
  { id: 199, slug: "slowking", types: ["water", "psychic"] },
  { id: 200, slug: "misdreavus", types: ["ghost"] },
  { id: 215, slug: "sneasel", types: ["dark", "ice"] },
  { id: 223, slug: "remoraid", types: ["water"] },
  { id: 224, slug: "octillery", types: ["water"] },
  { id: 226, slug: "mantine", types: ["water", "flying"] },
  { id: 240, slug: "magby", types: ["fire"] },
  { id: 298, slug: "azurill", types: ["normal", "fairy"] },
];

const ALL_EXCLUSIVES = [
  ...FIRE_RED.map((p) => ({ ...p, edition: "fire" })),
  ...LEAF_GREEN.map((p) => ({ ...p, edition: "leaf" })),
];

/* Etiquetas de tipos en español para la UI */
const TYPE_ES = {
  normal: "Normal",
  fire: "Fuego",
  water: "Agua",
  grass: "Planta",
  electric: "Eléctrico",
  ice: "Hielo",
  fighting: "Lucha",
  poison: "Veneno",
  ground: "Tierra",
  flying: "Volador",
  psychic: "Psíquico",
  bug: "Bicho",
  rock: "Roca",
  ghost: "Fantasma",
  dark: "Siniestro",
  dragon: "Dragón",
  steel: "Acero",
  fairy: "Hada",
};

/* Dónde capturarlos, según RankedBoost FRLG
   (https://rankedboost.com/pokemon/pokedex/firered-leafgreen/).
   w: [zona, método, niveles, % aparición] · e: [pre-evolución, cómo evoluciona] o null. */
const LOC = {
  23: { w: [["Ruta 4", "Hierba", "Nv 6–12", "25%"], ["Ruta 11", "Hierba", "Nv 12–15", "40%"], ["Ruta 9", "Hierba", "Nv 11–17", "25%"]], e: null },
  24: { w: [["Ruta 23", "Hierba", "Nv 44", "5%"], ["Calle Victoria", "Hierba", "Nv 44–46", "5%"]], e: ["Ekans", "Nv 22"] },
  43: { w: [["Ruta 24", "Hierba", "Nv 12–14", "25%"], ["Ruta 25", "Hierba", "Nv 12–14", "25%"], ["Ruta 5", "Hierba", "Nv 13–16", "25%"]], e: null },
  44: { w: [["Ruta 12", "Hierba", "Nv 28–30", "5%"], ["Ruta 13", "Hierba", "Nv 28–30", "5%"], ["Ruta 14", "Hierba", "Nv 30", "5%"]], e: ["Oddish", "Nv 21"] },
  45: { w: [], e: ["Gloom", "Piedra Hoja"] },
  54: { w: [["Ciudad Verde", "Surf", "Nv 20–40", "100%"], ["Ruta 25", "Surf", "Nv 20–40"], ["Ruta 6", "Surf", "Nv 20–40"]], e: null },
  55: { w: [["Islas Espuma", "Hierba", "Nv 32–35", "15%"], ["Islas Espuma", "Surf", "Nv 35–40"], ["Cabo Brink", "Surf", "Nv 35–40", "5%"]], e: ["Psyduck", "Nv 33"] },
  58: { w: [["Ruta 8", "Hierba", "Nv 15–18", "20%"], ["Ruta 7", "Hierba", "Nv 18–20", "10%"], ["Mansión Pokémon", "Hierba", "Nv 30–32", "15%"]], e: null },
  59: { w: [], e: ["Growlithe", "Piedra Fuego"] },
  90: { w: [["Pueblo Paleta", "Pesca (supercaña)", "Nv 15–25", "40%"], ["Ciudad Carmín", "Pesca (supercaña)", "Nv 15–25", "40%"], ["Isla Canela", "Pesca (supercaña)", "Nv 15–25", "40%"]], e: null },
  91: { w: [], e: ["Shellder", "Piedra Agua"] },
  123: { w: [["Ciudad Azulona", "Premio del casino", "Nv 25"], ["Zona Safari", "Hierba", "Nv 23–28", "4%"]], e: null },
  125: { w: [["Central Eléctrica", "Hierba", "Nv 32–35", "5%"]], e: null },
  182: { w: [], e: ["Gloom", "Piedra Solar"] },
  194: { w: [["Isla Cuarta", "Surf", "Nv 5–25", "70%"], ["Valle Ruinas", "Surf", "Nv 5–25", "100%"], ["Cueva Cascada", "Surf", "Nv 5–15", "5%"]], e: null },
  195: { w: [], e: ["Wooper", "Nv 20"] },
  198: { w: [["Cueva Perdida", "Hierba", "Nv 15–22", "20%"]], e: null },
  211: { w: [["Laberinto Acuático", "Pesca (supercaña)", "Nv 15–25", "40%"], ["Pradera Isla Cinco", "Pesca (supercaña)", "Nv 15–25", "40%"], ["Pilar Recuerdo", "Pesca (supercaña)", "Nv 15–25"]], e: null },
  212: { w: [], e: ["Scyther", "Intercambio con Revestimiento Metálico"] },
  225: { w: [["Cueva Cascada", "Hierba", "Nv 30", "5%"]], e: null },
  227: { w: [["Cañón Sevault", "Hierba", "Nv 30", "5%"]], e: null },
  239: { w: [], e: ["Electabuzz", "Crianza (huevo)"] },
  27: { w: [["Ruta 4", "Hierba", "Nv 6–12", "25%"], ["Ruta 11", "Hierba", "Nv 12–15", "40%"], ["Ruta 9", "Hierba", "Nv 11–17", "25%"]], e: null },
  28: { w: [["Ruta 23", "Hierba", "Nv 44", "5%"], ["Calle Victoria", "Hierba", "Nv 44–46", "5%"]], e: ["Sandshrew", "Nv 22"] },
  37: { w: [["Ruta 8", "Hierba", "Nv 15–18", "20%"], ["Ruta 7", "Hierba", "Nv 18–20", "10%"], ["Mansión Pokémon", "Hierba", "Nv 30–32", "15%"]], e: null },
  38: { w: [], e: ["Vulpix", "Piedra Fuego"] },
  69: { w: [["Ruta 24", "Hierba", "Nv 12–14", "25%"], ["Ruta 25", "Hierba", "Nv 12–14", "25%"], ["Ruta 5", "Hierba", "Nv 13–16", "25%"]], e: null },
  70: { w: [["Ruta 12", "Hierba", "Nv 28–30", "5%"], ["Ruta 13", "Hierba", "Nv 28–30", "5%"], ["Ruta 14", "Hierba", "Nv 30", "5%"]], e: ["Bellsprout", "Nv 21"] },
  71: { w: [], e: ["Weepinbell", "Piedra Hoja"] },
  79: { w: [["Ciudad Verde", "Surf", "Nv 20–40", "100%"], ["Ruta 25", "Surf", "Nv 20–40"], ["Ruta 6", "Surf", "Nv 20–40"]], e: null },
  80: { w: [["Islas Espuma", "Hierba", "Nv 32–35", "15%"], ["Islas Espuma", "Surf", "Nv 35–40"], ["Cabo Brink", "Surf", "Nv 35–40", "5%"]], e: ["Slowpoke", "Nv 37"] },
  120: { w: [["Pueblo Paleta", "Pesca (supercaña)", "Nv 15–25", "40%"], ["Ciudad Carmín", "Pesca (supercaña)", "Nv 15–25", "40%"], ["Isla Canela", "Pesca (supercaña)", "Nv 15–25", "40%"]], e: null },
  121: { w: [], e: ["Staryu", "Piedra Agua"] },
  126: { w: [["Monte Ember", "Hierba", "Nv 38–40", "5%"]], e: null },
  127: { w: [["Ciudad Azulona", "Premio del casino", "Nv 18"], ["Zona Safari", "Hierba", "Nv 23–28", "4%"]], e: null },
  183: { w: [["Isla Cuarta", "Surf", "Nv 5–25", "70%"], ["Valle Ruinas", "Surf", "Nv 5–25", "100%"], ["Cueva Cascada", "Surf", "Nv 5–15", "5%"]], e: ["Azurill", "Amistad"] },
  184: { w: [], e: ["Marill", "Nv 18"] },
  199: { w: [], e: ["Slowpoke", "Intercambio con Roca del Rey"] },
  200: { w: [["Cueva Perdida", "Hierba", "Nv 15–22", "20%"]], e: null },
  215: { w: [["Cueva Cascada", "Hierba", "Nv 30", "5%"]], e: null },
  223: { w: [["Laberinto Acuático", "Pesca (supercaña)", "Nv 15–25", "40%"], ["Pradera Isla Cinco", "Pesca (supercaña)", "Nv 15–25", "40%"], ["Pilar Recuerdo", "Pesca (supercaña)", "Nv 15–25"]], e: null },
  224: { w: [], e: ["Remoraid", "Nv 25"] },
  226: { w: [["Torre Entrenadores", "Surf", "Nv 35–40", "5%"]], e: null },
  240: { w: [], e: ["Magmar", "Crianza (huevo)"] },
  298: { w: [], e: ["Marill", "Crianza (huevo)"] },
  1: { w: [], e: [null, "Inicial (Pueblo Paleta)"]},
  2: { w: [], e: ["bulbasaur", "Nv 16"]},
  3: { w: [], e: ["ivysaur", "Nv 32"]},
  4: { w: [], e: [null, "Inicial (Pueblo Paleta)"]},
  5: { w: [], e: ["charmander", "Nv 16"]},
  6: { w: [], e: ["charmeleon", "Nv 36"]},
  7: { w: [], e: [null, "Inicial (Pueblo Paleta)"]},
  8: { w: [], e: ["squirtle", "Nv 16"]},
  9: { w: [], e: ["wartortle", "Nv 36"]},
  10: { w: [["Ruta 2", "Hierba", "Nv 4–5", "5%"], ["Bosque Verde", "Hierba", "Nv 3–5", "40%"], ["Ruta 24", "Hierba", "Nv 7", "20%"]], e: null},
  11: { w: [["Bosque Verde", "Hierba", "Nv 4–6", "10%"], ["Ruta 24", "Hierba", "Nv 8", "4%"], ["Ruta 25", "Hierba", "Nv 9", "4%"]], e: ["caterpie", "Nv 7"]},
  12: { w: [], e: ["metapod", "Nv 10"]},
  13: { w: [["Ruta 2", "Hierba", "Nv 4–5", "5%"], ["Bosque Verde", "Hierba", "Nv 3–5", "40%"], ["Ruta 24", "Hierba", "Nv 7", "20%"]], e: null},
  14: { w: [["Bosque Verde", "Hierba", "Nv 4–6", "10%"], ["Ruta 24", "Hierba", "Nv 8", "4%"], ["Ruta 25", "Hierba", "Nv 9", "4%"]], e: ["weedle", "Nv 7"]},
  15: { w: [], e: ["kakuna", "Nv 10"]},
  16: { w: [["Ruta 1", "Hierba", "Nv 2–5", "50%"], ["Ruta 2", "Hierba", "Nv 2–5", "45%"], ["Ruta 3", "Hierba", "Nv 6–7", "30%"]], e: null},
  17: { w: [["Ruta 13", "Hierba", "Nv 29", "5%"], ["Ruta 14", "Hierba", "Nv 29", "5%"], ["Ruta 15", "Hierba", "Nv 29", "5%"]], e: ["pidgey", "Nv 18"]},
  18: { w: [], e: ["pidgeotto", "Nv 36"]},
  19: { w: [["Ruta 1", "Hierba", "Nv 2–4", "50%"], ["Ruta 2", "Hierba", "Nv 2–5", "45%"], ["Ruta 4", "Hierba", "Nv 8–12", "35%"]], e: null},
  20: { w: [["Ruta 18", "Hierba", "Nv 25–29", "15%"], ["Ruta 17", "Hierba", "Nv 25–29", "25%"], ["Ruta 16", "Hierba", "Nv 23–25", "5%"]], e: ["rattata", "Nv 20"]},
  21: { w: [["Ruta 3", "Hierba", "Nv 6–8", "35%"], ["Ruta 4", "Hierba", "Nv 8–12", "35%"], ["Ruta 11", "Hierba", "Nv 13–17", "35%"]], e: null},
  22: { w: [["Ruta 18", "Hierba", "Nv 25–29", "15%"], ["Ruta 17", "Hierba", "Nv 25–27", "5%"], ["Playa Tesoro", "Hierba", "Nv 36–40", "20%"]], e: ["spearow", "Nv 20"]},
  25: { w: [["Bosque Verde", "Hierba", "Nv 3–5", "5%"], ["Central Eléctrica", "Hierba", "Nv 22–26", "25%"]], e: null},
  26: { w: [], e: ["pikachu", "Piedra Trueno"]},
  29: { w: [["Ruta 3", "Hierba", "Nv 6–7", "14%"], ["Zona Safari", "Hierba", "Nv 22–30", "20%"], ["Paso Subterráneo", "Intercambio interno", null, null]], e: null},
  30: { w: [["Ruta 11", "Intercambio interno", null, null], ["Zona Safari", "Hierba", "Nv 30–33", "10%"]], e: ["nidoran-f", "Nv 16"]},
  31: { w: [], e: ["nidorina", "Piedra Lunar"]},
  32: { w: [["Ruta 3", "Hierba", "Nv 6–7", "14%"], ["Zona Safari", "Hierba", "Nv 22–30", "20%"], ["Paso Subterráneo", "Intercambio interno", null, null]], e: null},
  33: { w: [["Ruta 11", "Intercambio interno", null, null], ["Zona Safari", "Hierba", "Nv 30–33", "10%"]], e: ["nidoran-m", "Nv 16"]},
  34: { w: [], e: ["nidorino", "Piedra Lunar"]},
  35: { w: [["Monte Moon", "Hierba", "Nv 8–12", "6%"], ["Ciudad Azulona", "Regalo NPC", "Nv 8–12", null]], e: null},
  36: { w: [], e: ["clefairy", "Piedra Lunar"]},
  39: { w: [["Ruta 3", "Hierba", "Nv 3–7", "10%"]], e: null},
  40: { w: [], e: ["jigglypuff", "Piedra Lunar"]},
  41: { w: [["Monte Moon", "Hierba", "Nv 7–11", "69%"], ["Túnel Roca", "Hierba", "Nv 15–16", "30%"], ["Islas Espuma", "Hierba", "Nv 22–26", "34%"]], e: null},
  42: { w: [["Islas Espuma", "Hierba", "Nv 26–30", "15%"], ["Calle Victoria", "Hierba", "Nv 44–46", "5%"], ["Cueva Cascada", "Hierba", "Nv 45–48", "25%"]], e: ["zubat", "Nv 22"]},
  46: { w: [["Monte Moon", "Hierba", "Nv 5–12", "100%"], ["Zona Safari", "Hierba", "Nv 22–23", "15%"]], e: null},
  47: { w: [["Zona Safari", "Hierba", "Nv 25–30", "5%"], ["Cueva Celeste", "Hierba", "Nv 49–64", "25%"]], e: ["paras", "Nv 24"]},
  48: { w: [["Ruta 12", "Hierba", "Nv 24–26", "30%"], ["Ruta 13", "Hierba", "Nv 24–26", "30%"], ["Ruta 14", "Hierba", "Nv 24–26", "30%"]], e: null},
  49: { w: [["Zona Safari", "Hierba", "Nv 32", "5%"], ["Bosque Baya", "Hierba", "Nv 37–40", "5%"]], e: ["venonat", "Nv 31"]},
  50: { w: [["Cueva Diglett", "Hierba", "Nv 15–22", "95%"]], e: null},
  51: { w: [["Cueva Diglett", "Hierba", "Nv 29–31", "5%"]], e: ["diglett", "Nv 26"]},
  52: { w: [["Ruta 5", "Hierba", "Nv 10–16", "35%"], ["Ruta 6", "Hierba", "Nv 10–16", "35%"], ["Ruta 8", "Hierba", "Nv 18–20", "30%"]], e: null},
  53: { w: [["Playa Tesoro", "Hierba", "Nv 37–40", "5%"], ["Camino Kindle", "Hierba", "Nv 37–40", "5%"], ["Cabo Brink", "Hierba", "Nv 37–40", "5%"]], e: ["meowth", "Nv 28"]},
  56: { w: [["Ruta 3", "Hierba", "Nv 7", "10%"], ["Ruta 4", "Hierba", "Nv 10–12", "5%"], ["Túnel Roca", "Hierba", "Nv 16–17", "15%"]], e: null},
  57: { w: [["Ruta 23", "Hierba", "Nv 42", "5%"], ["Calle Victoria", "Hierba", "Nv 42", "10%"]], e: ["mankey", "Nv 28"]},
  60: { w: [["Ciudad Verde", "Pesca (caña buena)", "Nv 5–15", "60%"], ["Ciudad Verde", "Pesca (supercaña)", "Nv 15–25", "40%"], ["Ruta 25", "Pesca (caña buena)", "Nv 5–15", "60%"]], e: null},
  61: { w: [["Ciudad Verde", "Pesca (supercaña)", "Nv 20–30", "40%"], ["Ruta 25", "Pesca (supercaña)", "Nv 20–30", "40%"], ["Ruta 6", "Pesca (supercaña)", "Nv 20–30", "40%"]], e: ["poliwag", "Nv 25"]},
  62: { w: [], e: ["poliwhirl", "Piedra Agua"]},
  63: { w: [["Ruta 24", "Hierba", "Nv 8–12", "15%"], ["Ruta 25", "Hierba", "Nv 9–13", "15%"]], e: null},
  64: { w: [], e: ["abra", "Nv 16"]},
  65: { w: [], e: ["kadabra", "Intercambio"]},
  66: { w: [["Túnel Roca", "Hierba", "Nv 16–17", "15%"], ["Monte Ascuas", "Hierba", "Nv 31–39", "50%"], ["Calle Victoria", "Hierba", "Nv 32–34", "20%"]], e: null},
  67: { w: [["Monte Ascuas", "Hierba", "Nv 38–42", "20%"], ["Calle Victoria", "Hierba", "Nv 44–48", "5%"]], e: ["machop", "Nv 28"]},
  68: { w: [], e: ["machoke", "Intercambio"]},
  72: { w: [["Pueblo Paleta", "Surf", "Nv 5–40", "100%"], ["Ruta 4", "Surf", "Nv 5–40", "100%"], ["Ciudad Celeste", "Surf", "Nv 5–40", "100%"]], e: null},
  73: { w: [["Isla Prima", "Surf", "Nv 35–40", "5%"], ["Playa Tesoro", "Surf", "Nv 35–40", "5%"], ["Camino Kindle", "Surf", "Nv 35–40", "5%"]], e: ["tentacool", "Nv 30"]},
  74: { w: [["Monte Moon", "Hierba", "Nv 7–10", "30%"], ["Túnel Roca", "Hierba", "Nv 15–17", "35%"], ["Camino Kindle", "Hierba", "Nv 31", "10%"]], e: null},
  75: { w: [["Túnel Roca", "Golpe Roca", "Nv 25–40", "5%"], ["Camino Kindle", "Golpe Roca", "Nv 25–40", "5%"], ["Monte Ascuas", "Golpe Roca", "Nv 25–50", "35%"]], e: ["geodude", "Nv 25"]},
  76: { w: [], e: ["graveler", "Intercambio"]},
  77: { w: [["Camino Kindle", "Hierba", "Nv 31–34", "30%"], ["Monte Ascuas", "Hierba", "Nv 30–36", "35%"]], e: null},
  78: { w: [["Camino Kindle", "Hierba", "Nv 37–40", "5%"], ["Monte Ascuas", "Hierba", "Nv 39–42", "5%"]], e: ["ponyta", "Nv 40"]},
  81: { w: [["Central Eléctrica", "Hierba", "Nv 22–25", "30%"]], e: null},
  82: { w: [["Central Eléctrica", "Hierba", "Nv 31–34", "15%"]], e: ["magnemite", "Nv 30"]},
  83: { w: [], e: [null, "Intercambio"]},
  84: { w: [["Ruta 18", "Hierba", "Nv 24–28", "35%"], ["Ruta 17", "Hierba", "Nv 24–28", "35%"], ["Ruta 16", "Hierba", "Nv 18–22", "35%"]], e: null},
  85: { w: [], e: ["doduo", "Nv 31"]},
  86: { w: [["Islas Espuma", "Surf", "Nv 25–35", "60%"], ["Islas Espuma", "Hierba", "Nv 28–34", "50%"], ["Cueva Cascada", "Surf", "Nv 5–35", "60%"]], e: null},
  87: { w: [["Islas Espuma", "Hierba", "Nv 32–36", "10%"], ["Islas Espuma", "Surf", "Nv 35–40", "5%"], ["Cueva Cascada", "Hierba", "Nv 49–53", "20%"]], e: ["seel", "Nv 34"]},
  88: { w: [["Mansión Pokémon", "Hierba", "Nv 28–30", "30%"], ["Ciudad Azulona", "Pesca (supercaña)", "Nv 30–40", "1%"]], e: null},
  89: { w: [["Mansión Pokémon", "Hierba", "Nv 32–34", "5%"]], e: ["grimer", "Nv 38"]},
  92: { w: [["Torre Pokemon", "Hierba", "Nv 13–19", "90%"], ["Cueva Perdida", "Hierba", "Nv 38–40", "25%"]], e: null},
  93: { w: [["Torre Pokemon", "Hierba", "Nv 20–25", "15%"], ["Cueva Perdida", "Hierba", "Nv 44–52", "30%"]], e: ["gastly", "Nv 25"]},
  94: { w: [], e: ["haunter", "Intercambio"]},
  95: { w: [["Túnel Roca", "Hierba", "Nv 13–17", "10%"], ["Calle Victoria", "Hierba", "Nv 40–48", "30%"]], e: null},
  96: { w: [["Ruta 11", "Hierba", "Nv 11–15", "25%"], ["Bosque Baya", "Hierba", "Nv 34", "10%"]], e: null},
  97: { w: [["Bosque Baya", "Hierba", "Nv 37–40", "5%"], ["Bosque Baya", "Estático", "Nv 30", null]], e: ["drowzee", "Nv 26"]},
  98: { w: [["Ruta 4", "Pesca (supercaña)", "Nv 15–35", "84%"], ["Ruta 10", "Pesca (supercaña)", "Nv 15–35", "84%"], ["Islas Espuma", "Pesca (supercaña)", "Nv 15–30", "80%"]], e: null},
  99: { w: [["Pueblo Paleta", "Pesca (supercaña)", "Nv 25–35", "4%"], ["Ruta 19", "Pesca (supercaña)", "Nv 25–35", "4%"], ["Ruta 20", "Pesca (supercaña)", "Nv 25–35", "4%"]], e: ["krabby", "Nv 28"]},
  100: { w: [["Ruta 10", "Hierba", "Nv 14–17", "40%"], ["Central Eléctrica", "Hierba", "Nv 22–25", "30%"]], e: null},
  101: { w: [["Central Eléctrica", "Estático", "Nv 34", null]], e: ["voltorb", "Nv 30"]},
  102: { w: [["Zona Safari", "Hierba", "Nv 23–27", "20%"], ["Bosque Baya", "Hierba", "Nv 35", "5%"]], e: null},
  103: { w: [], e: ["exeggcute", "Piedra Hoja"]},
  104: { w: [["Torre Pokemon", "Hierba", "Nv 15–19", "10%"], ["Cañon Sevault", "Hierba", "Nv 46", "10%"]], e: null},
  105: { w: [["Torre Pokemon", "Estático", "Nv 30", null], ["Calle Victoria", "Hierba", "Nv 44–48", "5%"], ["Cañon Sevault", "Hierba", "Nv 52", "10%"]], e: ["cubone", "Nv 28"]},
  106: { w: [], e: [null, "Regalo"]},
  107: { w: [], e: [null, "Regalo"]},
  108: { w: [], e: [null, "Intercambio"]},
  109: { w: [["Mansión Pokémon", "Hierba", "Nv 28–30", "30%"], ["Ciudad Azulona", "Surf", "Nv 30–40", "1%"]], e: null},
  110: { w: [["Mansión Pokémon", "Hierba", "Nv 32–34", "5%"]], e: ["koffing", "Nv 35"]},
  111: { w: [["Zona Safari", "Hierba", "Nv 25–26", "20%"]], e: null},
  112: { w: [], e: ["rhyhorn", "Nv 42"]},
  113: { w: [["Zona Safari", "Hierba", "Nv 23–26", "4%"]], e: null},
  114: { w: [["Ruta 21", "Hierba", "Nv 17–28", "100%"], ["Playa Tesoro", "Hierba", "Nv 33–35", "30%"]], e: null},
  115: { w: [["Zona Safari", "Hierba", "Nv 25–28", "4%"]], e: null},
  116: { w: [["Ruta 4", "Pesca (supercaña)", "Nv 15–35", "84%"], ["Ruta 10", "Pesca (supercaña)", "Nv 15–35", "84%"], ["Islas Espuma", "Pesca (supercaña)", "Nv 15–30", "80%"]], e: null},
  117: { w: [["Pueblo Paleta", "Pesca (supercaña)", "Nv 25–35", "4%"], ["Ruta 19", "Pesca (supercaña)", "Nv 25–35", "4%"], ["Ruta 20", "Pesca (supercaña)", "Nv 25–35", "4%"]], e: ["horsea", "Nv 32"]},
  118: { w: [["Zona Safari", "Pesca (caña buena)", "Nv 5–15", "60%"], ["Ciudad Fucsia", "Pesca (caña buena)", "Nv 5–15", "60%"], ["Zona Safari", "Pesca (supercaña)", "Nv 15–25", "40%"]], e: null},
  119: { w: [["Zona Safari", "Pesca (supercaña)", "Nv 20–30", "40%"], ["Ciudad Fucsia", "Pesca (supercaña)", "Nv 20–30", "40%"], ["Bosque Baya", "Pesca (supercaña)", "Nv 20–30", "40%"]], e: ["goldeen", "Nv 33"]},
  122: { w: [], e: [null, "Intercambio"]},
  124: { w: [], e: [null, "Intercambio"]},
  128: { w: [["Zona Safari", "Hierba", "Nv 25–28", "4%"]], e: null},
  129: { w: [["Pueblo Paleta", "Pesca (caña vieja)", "Nv 5–10", "100%"], ["Ruta 4", "Pesca (caña vieja)", "Nv 5", "100%"], ["Ciudad Azulona", "Pesca (supercaña)", "Nv 15–35", "99%"]], e: null},
  130: { w: [["Ruta 6", "Pesca (supercaña)", "Nv 15–25", "15%"], ["Ruta 4", "Pesca (supercaña)", "Nv 15–25", "15%"], ["Islas Espuma", "Pesca (supercaña)", "Nv 15–35", "16%"]], e: ["magikarp", "Nv 20"]},
  131: { w: [["Edificio Silph", "Regalo NPC", "Nv 25", null], ["Cueva Cascada", "Surf", "Nv 30–45", "1%"]], e: null},
  132: { w: [["Ruta 14", "Hierba", "Nv 23", "15%"], ["Ruta 13", "Hierba", "Nv 25", "5%"], ["Mansión Pokémon", "Hierba", "Nv 30", "10%"]], e: null},
  133: { w: [], e: [null, "Regalo"]},
  134: { w: [], e: ["eevee", "Piedra Agua"]},
  135: { w: [], e: ["eevee", "Piedra Trueno"]},
  136: { w: [], e: ["eevee", "Piedra Fuego"]},
  137: { w: [], e: [null, "Casino"]},
  138: { w: [], e: [null, "Fósil"]},
  139: { w: [], e: ["omanyte", "Nv 40"]},
  140: { w: [], e: [null, "Fósil"]},
  141: { w: [], e: ["kabuto", "Nv 40"]},
  142: { w: [], e: [null, "Fósil"]},
  143: { w: [], e: [null, "Estático"]},
  144: { w: [], e: [null, "Estático"]},
  145: { w: [], e: [null, "Estático"]},
  146: { w: [], e: [null, "Estático"]},
  147: { w: [["Zona Safari", "Pesca (supercaña)", "Nv 15–25", "15%"], ["Ciudad Azulona", "Regalo NPC", "Nv 18–24", null]], e: null},
  148: { w: [["Zona Safari", "Pesca (supercaña)", "Nv 25–35", "1%"]], e: ["dratini", "Nv 30"]},
  149: { w: [], e: ["dragonair", "Nv 55"]},
  150: { w: [], e: [null, "Estático"]},
  151: { w: [], e: null},
  243: { w: [["Hierba de Kanto", "Itinerante (post-Liga)", "Nv 50", null]], e: null},
  244: { w: [["Hierba de Kanto", "Itinerante (post-Liga)", "Nv 50", null]], e: null},
  245: { w: [["Hierba de Kanto", "Itinerante (post-Liga)", "Nv 50", null]], e: null},
  249: { w: [["Roca Ombligo", "Evento", "Nv 70", null]], e: null},
  250: { w: [["Roca Ombligo", "Evento", "Nv 70", null]], e: null},

};

/* Pokédex completa: Kanto (1-151) + Johto (152-251). */
const DEX_ALL = [
  { id: 1, slug: "bulbasaur" },
  { id: 2, slug: "ivysaur" },
  { id: 3, slug: "venusaur" },
  { id: 4, slug: "charmander" },
  { id: 5, slug: "charmeleon" },
  { id: 6, slug: "charizard" },
  { id: 7, slug: "squirtle" },
  { id: 8, slug: "wartortle" },
  { id: 9, slug: "blastoise" },
  { id: 10, slug: "caterpie" },
  { id: 11, slug: "metapod" },
  { id: 12, slug: "butterfree" },
  { id: 13, slug: "weedle" },
  { id: 14, slug: "kakuna" },
  { id: 15, slug: "beedrill" },
  { id: 16, slug: "pidgey" },
  { id: 17, slug: "pidgeotto" },
  { id: 18, slug: "pidgeot" },
  { id: 19, slug: "rattata" },
  { id: 20, slug: "raticate" },
  { id: 21, slug: "spearow" },
  { id: 22, slug: "fearow" },
  { id: 23, slug: "ekans" },
  { id: 24, slug: "arbok" },
  { id: 25, slug: "pikachu" },
  { id: 26, slug: "raichu" },
  { id: 27, slug: "sandshrew" },
  { id: 28, slug: "sandslash" },
  { id: 29, slug: "nidoran-f" },
  { id: 30, slug: "nidorina" },
  { id: 31, slug: "nidoqueen" },
  { id: 32, slug: "nidoran-m" },
  { id: 33, slug: "nidorino" },
  { id: 34, slug: "nidoking" },
  { id: 35, slug: "clefairy" },
  { id: 36, slug: "clefable" },
  { id: 37, slug: "vulpix" },
  { id: 38, slug: "ninetales" },
  { id: 39, slug: "jigglypuff" },
  { id: 40, slug: "wigglytuff" },
  { id: 41, slug: "zubat" },
  { id: 42, slug: "golbat" },
  { id: 43, slug: "oddish" },
  { id: 44, slug: "gloom" },
  { id: 45, slug: "vileplume" },
  { id: 46, slug: "paras" },
  { id: 47, slug: "parasect" },
  { id: 48, slug: "venonat" },
  { id: 49, slug: "venomoth" },
  { id: 50, slug: "diglett" },
  { id: 51, slug: "dugtrio" },
  { id: 52, slug: "meowth" },
  { id: 53, slug: "persian" },
  { id: 54, slug: "psyduck" },
  { id: 55, slug: "golduck" },
  { id: 56, slug: "mankey" },
  { id: 57, slug: "primeape" },
  { id: 58, slug: "growlithe" },
  { id: 59, slug: "arcanine" },
  { id: 60, slug: "poliwag" },
  { id: 61, slug: "poliwhirl" },
  { id: 62, slug: "poliwrath" },
  { id: 63, slug: "abra" },
  { id: 64, slug: "kadabra" },
  { id: 65, slug: "alakazam" },
  { id: 66, slug: "machop" },
  { id: 67, slug: "machoke" },
  { id: 68, slug: "machamp" },
  { id: 69, slug: "bellsprout" },
  { id: 70, slug: "weepinbell" },
  { id: 71, slug: "victreebel" },
  { id: 72, slug: "tentacool" },
  { id: 73, slug: "tentacruel" },
  { id: 74, slug: "geodude" },
  { id: 75, slug: "graveler" },
  { id: 76, slug: "golem" },
  { id: 77, slug: "ponyta" },
  { id: 78, slug: "rapidash" },
  { id: 79, slug: "slowpoke" },
  { id: 80, slug: "slowbro" },
  { id: 81, slug: "magnemite" },
  { id: 82, slug: "magneton" },
  { id: 83, slug: "farfetchd" },
  { id: 84, slug: "doduo" },
  { id: 85, slug: "dodrio" },
  { id: 86, slug: "seel" },
  { id: 87, slug: "dewgong" },
  { id: 88, slug: "grimer" },
  { id: 89, slug: "muk" },
  { id: 90, slug: "shellder" },
  { id: 91, slug: "cloyster" },
  { id: 92, slug: "gastly" },
  { id: 93, slug: "haunter" },
  { id: 94, slug: "gengar" },
  { id: 95, slug: "onix" },
  { id: 96, slug: "drowzee" },
  { id: 97, slug: "hypno" },
  { id: 98, slug: "krabby" },
  { id: 99, slug: "kingler" },
  { id: 100, slug: "voltorb" },
  { id: 101, slug: "electrode" },
  { id: 102, slug: "exeggcute" },
  { id: 103, slug: "exeggutor" },
  { id: 104, slug: "cubone" },
  { id: 105, slug: "marowak" },
  { id: 106, slug: "hitmonlee" },
  { id: 107, slug: "hitmonchan" },
  { id: 108, slug: "lickitung" },
  { id: 109, slug: "koffing" },
  { id: 110, slug: "weezing" },
  { id: 111, slug: "rhyhorn" },
  { id: 112, slug: "rhydon" },
  { id: 113, slug: "chansey" },
  { id: 114, slug: "tangela" },
  { id: 115, slug: "kangaskhan" },
  { id: 116, slug: "horsea" },
  { id: 117, slug: "seadra" },
  { id: 118, slug: "goldeen" },
  { id: 119, slug: "seaking" },
  { id: 120, slug: "staryu" },
  { id: 121, slug: "starmie" },
  { id: 122, slug: "mr-mime" },
  { id: 123, slug: "scyther" },
  { id: 124, slug: "jynx" },
  { id: 125, slug: "electabuzz" },
  { id: 126, slug: "magmar" },
  { id: 127, slug: "pinsir" },
  { id: 128, slug: "tauros" },
  { id: 129, slug: "magikarp" },
  { id: 130, slug: "gyarados" },
  { id: 131, slug: "lapras" },
  { id: 132, slug: "ditto" },
  { id: 133, slug: "eevee" },
  { id: 134, slug: "vaporeon" },
  { id: 135, slug: "jolteon" },
  { id: 136, slug: "flareon" },
  { id: 137, slug: "porygon" },
  { id: 138, slug: "omanyte" },
  { id: 139, slug: "omastar" },
  { id: 140, slug: "kabuto" },
  { id: 141, slug: "kabutops" },
  { id: 142, slug: "aerodactyl" },
  { id: 143, slug: "snorlax" },
  { id: 144, slug: "articuno" },
  { id: 145, slug: "zapdos" },
  { id: 146, slug: "moltres" },
  { id: 147, slug: "dratini" },
  { id: 148, slug: "dragonair" },
  { id: 149, slug: "dragonite" },
  { id: 150, slug: "mewtwo" },
  { id: 151, slug: "mew" },
  { id: 152, slug: "chikorita" },
  { id: 153, slug: "bayleef" },
  { id: 154, slug: "meganium" },
  { id: 155, slug: "cyndaquil" },
  { id: 156, slug: "quilava" },
  { id: 157, slug: "typhlosion" },
  { id: 158, slug: "totodile" },
  { id: 159, slug: "croconaw" },
  { id: 160, slug: "feraligatr" },
  { id: 161, slug: "sentret" },
  { id: 162, slug: "furret" },
  { id: 163, slug: "hoothoot" },
  { id: 164, slug: "noctowl" },
  { id: 165, slug: "ledyba" },
  { id: 166, slug: "ledian" },
  { id: 167, slug: "spinarak" },
  { id: 168, slug: "ariados" },
  { id: 169, slug: "crobat" },
  { id: 170, slug: "chinchou" },
  { id: 171, slug: "lanturn" },
  { id: 172, slug: "pichu" },
  { id: 173, slug: "cleffa" },
  { id: 174, slug: "igglybuff" },
  { id: 175, slug: "togepi" },
  { id: 176, slug: "togetic" },
  { id: 177, slug: "natu" },
  { id: 178, slug: "xatu" },
  { id: 179, slug: "mareep" },
  { id: 180, slug: "flaaffy" },
  { id: 181, slug: "ampharos" },
  { id: 182, slug: "bellossom" },
  { id: 183, slug: "marill" },
  { id: 184, slug: "azumarill" },
  { id: 185, slug: "sudowoodo" },
  { id: 186, slug: "politoed" },
  { id: 187, slug: "hoppip" },
  { id: 188, slug: "skiploom" },
  { id: 189, slug: "jumpluff" },
  { id: 190, slug: "aipom" },
  { id: 191, slug: "sunkern" },
  { id: 192, slug: "sunflora" },
  { id: 193, slug: "yanma" },
  { id: 194, slug: "wooper" },
  { id: 195, slug: "quagsire" },
  { id: 196, slug: "espeon" },
  { id: 197, slug: "umbreon" },
  { id: 198, slug: "murkrow" },
  { id: 199, slug: "slowking" },
  { id: 200, slug: "misdreavus" },
  { id: 201, slug: "unown" },
  { id: 202, slug: "wobbuffet" },
  { id: 203, slug: "girafarig" },
  { id: 204, slug: "pineco" },
  { id: 205, slug: "forretress" },
  { id: 206, slug: "dunsparce" },
  { id: 207, slug: "gligar" },
  { id: 208, slug: "steelix" },
  { id: 209, slug: "snubbull" },
  { id: 210, slug: "granbull" },
  { id: 211, slug: "qwilfish" },
  { id: 212, slug: "scizor" },
  { id: 213, slug: "shuckle" },
  { id: 214, slug: "heracross" },
  { id: 215, slug: "sneasel" },
  { id: 216, slug: "teddiursa" },
  { id: 217, slug: "ursaring" },
  { id: 218, slug: "slugma" },
  { id: 219, slug: "magcargo" },
  { id: 220, slug: "swinub" },
  { id: 221, slug: "piloswine" },
  { id: 222, slug: "corsola" },
  { id: 223, slug: "remoraid" },
  { id: 224, slug: "octillery" },
  { id: 225, slug: "delibird" },
  { id: 226, slug: "mantine" },
  { id: 227, slug: "skarmory" },
  { id: 228, slug: "houndour" },
  { id: 229, slug: "houndoom" },
  { id: 230, slug: "kingdra" },
  { id: 231, slug: "phanpy" },
  { id: 232, slug: "donphan" },
  { id: 233, slug: "porygon2" },
  { id: 234, slug: "stantler" },
  { id: 235, slug: "smeargle" },
  { id: 236, slug: "tyrogue" },
  { id: 237, slug: "hitmontop" },
  { id: 238, slug: "smoochum" },
  { id: 239, slug: "elekid" },
  { id: 240, slug: "magby" },
  { id: 241, slug: "miltank" },
  { id: 242, slug: "blissey" },
  { id: 243, slug: "raikou" },
  { id: 244, slug: "entei" },
  { id: 245, slug: "suicune" },
  { id: 246, slug: "larvitar" },
  { id: 247, slug: "pupitar" },
  { id: 248, slug: "tyranitar" },
  { id: 249, slug: "lugia" },
  { id: 250, slug: "ho-oh" },
  { id: 251, slug: "celebi" }
];

const TYPES_ALL = {
  1: ["grass", "poison"],
  2: ["grass", "poison"],
  3: ["grass", "poison"],
  4: ["fire"],
  5: ["fire"],
  6: ["fire", "flying"],
  7: ["water"],
  8: ["water"],
  9: ["water"],
  10: ["bug"],
  11: ["bug"],
  12: ["bug", "flying"],
  13: ["bug", "poison"],
  14: ["bug", "poison"],
  15: ["bug", "poison"],
  16: ["normal", "flying"],
  17: ["normal", "flying"],
  18: ["normal", "flying"],
  19: ["normal"],
  20: ["normal"],
  21: ["normal", "flying"],
  22: ["normal", "flying"],
  23: ["poison"],
  24: ["poison"],
  25: ["electric"],
  26: ["electric"],
  27: ["ground"],
  28: ["ground"],
  29: ["poison"],
  30: ["poison"],
  31: ["poison", "ground"],
  32: ["poison"],
  33: ["poison"],
  34: ["poison", "ground"],
  35: ["fairy"],
  36: ["fairy"],
  37: ["fire"],
  38: ["fire"],
  39: ["normal", "fairy"],
  40: ["normal", "fairy"],
  41: ["poison", "flying"],
  42: ["poison", "flying"],
  43: ["grass", "poison"],
  44: ["grass", "poison"],
  45: ["grass", "poison"],
  46: ["bug", "grass"],
  47: ["bug", "grass"],
  48: ["bug", "poison"],
  49: ["bug", "poison"],
  50: ["ground"],
  51: ["ground"],
  52: ["normal"],
  53: ["normal"],
  54: ["water"],
  55: ["water"],
  56: ["fighting"],
  57: ["fighting"],
  58: ["fire"],
  59: ["fire"],
  60: ["water"],
  61: ["water"],
  62: ["water", "fighting"],
  63: ["psychic"],
  64: ["psychic"],
  65: ["psychic"],
  66: ["fighting"],
  67: ["fighting"],
  68: ["fighting"],
  69: ["grass", "poison"],
  70: ["grass", "poison"],
  71: ["grass", "poison"],
  72: ["water", "poison"],
  73: ["water", "poison"],
  74: ["rock", "ground"],
  75: ["rock", "ground"],
  76: ["rock", "ground"],
  77: ["fire"],
  78: ["fire"],
  79: ["water", "psychic"],
  80: ["water", "psychic"],
  81: ["electric", "steel"],
  82: ["electric", "steel"],
  83: ["normal", "flying"],
  84: ["normal", "flying"],
  85: ["normal", "flying"],
  86: ["water"],
  87: ["water", "ice"],
  88: ["poison"],
  89: ["poison"],
  90: ["water"],
  91: ["water", "ice"],
  92: ["ghost", "poison"],
  93: ["ghost", "poison"],
  94: ["ghost", "poison"],
  95: ["rock", "ground"],
  96: ["psychic"],
  97: ["psychic"],
  98: ["water"],
  99: ["water"],
  100: ["electric"],
  101: ["electric"],
  102: ["grass", "psychic"],
  103: ["grass", "psychic"],
  104: ["ground"],
  105: ["ground"],
  106: ["fighting"],
  107: ["fighting"],
  108: ["normal"],
  109: ["poison"],
  110: ["poison"],
  111: ["ground", "rock"],
  112: ["ground", "rock"],
  113: ["normal"],
  114: ["grass"],
  115: ["normal"],
  116: ["water"],
  117: ["water"],
  118: ["water"],
  119: ["water"],
  120: ["water"],
  121: ["water", "psychic"],
  122: ["psychic", "fairy"],
  123: ["bug", "flying"],
  124: ["ice", "psychic"],
  125: ["electric"],
  126: ["fire"],
  127: ["bug"],
  128: ["normal"],
  129: ["water"],
  130: ["water", "flying"],
  131: ["water", "ice"],
  132: ["normal"],
  133: ["normal"],
  134: ["water"],
  135: ["electric"],
  136: ["fire"],
  137: ["normal"],
  138: ["rock", "water"],
  139: ["rock", "water"],
  140: ["rock", "water"],
  141: ["rock", "water"],
  142: ["rock", "flying"],
  143: ["normal"],
  144: ["ice", "flying"],
  145: ["electric", "flying"],
  146: ["fire", "flying"],
  147: ["dragon"],
  148: ["dragon"],
  149: ["dragon", "flying"],
  150: ["psychic"],
  151: ["psychic"],
  152: ["grass"],
  153: ["grass"],
  154: ["grass"],
  155: ["fire"],
  156: ["fire"],
  157: ["fire"],
  158: ["water"],
  159: ["water"],
  160: ["water"],
  161: ["normal"],
  162: ["normal"],
  163: ["normal", "flying"],
  164: ["normal", "flying"],
  165: ["bug", "flying"],
  166: ["bug", "flying"],
  167: ["bug", "poison"],
  168: ["bug", "poison"],
  169: ["poison", "flying"],
  170: ["water", "electric"],
  171: ["water", "electric"],
  172: ["electric"],
  173: ["fairy"],
  174: ["normal", "fairy"],
  175: ["fairy"],
  176: ["fairy", "flying"],
  177: ["psychic", "flying"],
  178: ["psychic", "flying"],
  179: ["electric"],
  180: ["electric"],
  181: ["electric"],
  182: ["grass"],
  183: ["water", "fairy"],
  184: ["water", "fairy"],
  185: ["rock"],
  186: ["water"],
  187: ["grass", "flying"],
  188: ["grass", "flying"],
  189: ["grass", "flying"],
  190: ["normal"],
  191: ["grass"],
  192: ["grass"],
  193: ["bug", "flying"],
  194: ["water", "ground"],
  195: ["water", "ground"],
  196: ["psychic"],
  197: ["dark"],
  198: ["dark", "flying"],
  199: ["water", "psychic"],
  200: ["ghost"],
  201: ["psychic"],
  202: ["psychic"],
  203: ["normal", "psychic"],
  204: ["bug"],
  205: ["bug", "steel"],
  206: ["normal"],
  207: ["ground", "flying"],
  208: ["steel", "ground"],
  209: ["fairy"],
  210: ["fairy"],
  211: ["water", "poison"],
  212: ["bug", "steel"],
  213: ["bug", "rock"],
  214: ["bug", "fighting"],
  215: ["dark", "ice"],
  216: ["normal"],
  217: ["normal"],
  218: ["fire"],
  219: ["fire", "rock"],
  220: ["ice", "ground"],
  221: ["ice", "ground"],
  222: ["water", "rock"],
  223: ["water"],
  224: ["water"],
  225: ["ice", "flying"],
  226: ["water", "flying"],
  227: ["steel", "flying"],
  228: ["dark", "fire"],
  229: ["dark", "fire"],
  230: ["water", "dragon"],
  231: ["ground"],
  232: ["ground"],
  233: ["normal"],
  234: ["normal"],
  235: ["normal"],
  236: ["fighting"],
  237: ["fighting"],
  238: ["ice", "psychic"],
  239: ["electric"],
  240: ["fire"],
  241: ["normal"],
  242: ["normal"],
  243: ["electric"],
  244: ["fire"],
  245: ["water"],
  246: ["rock", "ground"],
  247: ["rock", "ground"],
  248: ["rock", "dark"],
  249: ["psychic", "flying"],
  250: ["fire", "flying"],
  251: ["psychic", "grass"]
};

const NAME_FIX = {
  "nidoran-f": "Nidoran ♀",
  "nidoran-m": "Nidoran ♂",
  "farfetchd": "Farfetch'd",
  "mr-mime": "Mr. Mime",
  "ho-oh": "Ho-Oh"
};
