/* Playlist de YouTube: guía completa Rojo Fuego / Verde Hoja.
   Extraída de https://www.youtube.com/playlist?list=PLMa4xzilcmBt-tBff6_m3KsLrLWPwA_6X
   36 capítulos + 50 shorts. Para actualizarla, edita estas listas. */

const PLAYLIST_ID = "PLMa4xzilcmBt-tBff6_m3KsLrLWPwA_6X";

const EPISODES = [
  { id: "GYlCV2q-iWk", title: "Pokémon Rojo Fuego #1 - Bulbasaur, Charmander o Squirtle" },
  { id: "GoM-QMUjCoM", title: "Pokémon Rojo Fuego #2 - Ciudad Verde y Bosque Verde" },
  { id: "cyI142g2W3k", title: "Pokémon FireRed #3 - Pewter City. Gym Leader Brock. Buying Magikarp" },
  { id: "5RURayNFsug", title: "Pokémon FireRed #4 - Mt. Moon, Pokémon Fossil, and Team Rocket" },
  { id: "ZMN48mfG-lA", title: "Pokémon FireRed #5 - Cerulean City. Gym Leader Misty" },
  { id: "CP4YA0VX7c8", title: "Pokémon FireRed #6 - Nugget Bridge and Bill the Pokemaniac" },
  { id: "0aAzAGs2mOM", title: "Pokémon FireRed #7 - Vermillion City, Bike Bonus, Bicycle, Seekscapelea and Old Cane" },
  { id: "hFD4BL810_o", title: "Pokémon FireRed #8 - S.S. Anne" },
  { id: "0jHjuwEyOl8", title: "Pokémon Rojo Fuego #9 - Cueva Diglett, MO05 Destello y Buscaobjetos" },
  { id: "9wFECR-HQf0", title: "Pokémon FireRed #10 - Vermillion Gym. L.T. Surge Leader" },
  { id: "-rNbBsyPL4s", title: "Pokémon Rojo Fuego #11 - Túnel Roca ¡¡SIN DESTELLO!!" },
  { id: "4ETwT9q3oig", title: "Pokémon FireRed #12 - Celadon City, HM 02 Fly and Eevee" },
  { id: "e_KIuYFiUS8", title: "Pokémon Rojo Fuego #13 - Gimnasio Ciudad Azulona, Líder Erika" },
  { id: "cFEJysPugqM", title: "Pokémon FireRed #14 - Team Rocket's Lair" },
  { id: "dljVy0CTBRM", title: "Pokémon FireRed #15 - Pokémon Tower, Poké Flute and Snorlax" },
  { id: "-VeJ3sIpnGE", title: "Pokémon Rojo Fuego #16 - Silph S.A. Lapras y Master Ball" },
  { id: "NxidGrEKLzg", title: "Pokémon Rojo Fuego #17 - Ciudad Fucsia, Zona Safari, Repartir Exp y MO Surf y Fuerza" },
  { id: "fw5d77M7l_A", title: "Pokémon Rojo Fuego #18 - Ciudad Fucsia, Líder Koga y Supercaña" },
  { id: "ZBCbk_pab44", title: "Pokémon Rojo Fuego #19 - Ciudad Azafrán, Líder Sabrina y Gimnasio de Lucha" },
  { id: "TBLW95Jj89Q", title: "Pokémon FireRed #20 - Cinnabar Island, Old Amber and Aerodactyl" },
  { id: "AaNBXBi11ZE", title: "Pokémon FireRed #21 - Cinnabar Island, Pokémon Mansion and Gym Leader Blaine" },
  { id: "X6kkDIw2Qmk", title: "Pokémon Rojo Fuego #22 - Islas Prima, Secunda y Tera" },
  { id: "PXCBlqCPw1U", title: "Pokémon FireRed #23 - The Eighth Gym Badge" },
  { id: "8a5os37mJrY", title: "Pokémon Rojo Fuego #24 - Islas Espuma. Cómo Conseguir a ARTICUNO" },
  { id: "ZQd_eneY3mU", title: "Pokémon Rojo Fuego #25 - Central Energía. Cómo Conseguir a ZAPDOS" },
  { id: "ZV69u20fWfU", title: "Pokémon Rojo Fuego #26 - Monte Ascuas. Cómo Conseguir a MOLTRES" },
  { id: "74Br0OSAmt8", title: "Pokémon Rojo Fuego #27 - La calle victoria de Kanto" },
  { id: "PZE29Fstv0E", title: "Pokémon FireRed #28 - Pokémon League" },
  { id: "NhK2DUc5U54", title: "Pokémon FireRed #29 - National Pokédex, Ruby and Sapphire Tickets" },
  { id: "eZa3sidWkM4", title: "Pokémon Rojo Fuego #30 - Huevo de Togepi, Cueva Perdida y Ruinas Sete" },
  { id: "WkVwHsyy9DY", title: "Pokémon FireRed #31 - Icefall Cave, Dotted Hole, and Team Rocket Warehouse" },
  { id: "qtJA0cEI_MI", title: "Pokémon Rojo Fuego #32 - Cómo Conseguir a RAIKOU, ENTEI o SUICUNE" },
  { id: "jsBQdDzfZRY", title: "Pokémon FireRed #33 - Navel Rock. LUGIA and HO-OH" },
  { id: "TfOq2cLDE-M", title: "Pokémon Rojo Fuego #34 - Isla Origen. Deoxys" },
  { id: "tQp4fdnZtOA", title: "Pokémon FireRed #35 - Rare Dungeon / Cerulean Cave. MEWTWO" },
  { id: "MsWs2QRAOvE", title: "Pokémon FireRed #36 - The League's New Pokémon, Featuring Mewtwo" },
];

const SHORTS = [
  { id: "DF8Fp1IEZFY", title: "Which is the BEST STARTER in KANTO? ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "WgT3AQmcMH8", title: "How to get rid of the old man in Viridian City? ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "IJTsumPkB7g", title: "¿Cómo Conseguir a PIKACHU? ➤ Pokémon Rojo Fuego y Verde Hoja #shorts" },
  { id: "kJFDcwS2dVQ", title: "Is it a good idea to buy the Magikarp for $500? ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "u1cx27JLxps", title: "💎Fósil Helix Vs Fósil Domo💎 ➤ Pokémon Rojo Fuego y Verde Hoja #shorts" },
  { id: "66Wl0xPt92E", title: "🚲How to Get a FREE BICYCLE?🚲 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "XLvkJZtoEBI", title: "👊🏻How to get the Fighting Searcher?👊🏻 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "lsLIYLFUNrg", title: "💡How to get HM05 Flash?💡 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "WbpZWKzUWrM", title: "♂️ NIDOKING or NIDOQUEEN ♀️ WHICH IS BETTER? 👑➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "ZvQWHlm7J0E", title: "🥬How to Get Farfetch'd🥬 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "rv-NHRnD7Ow", title: "🔍How to get the Itemfinder?🔎 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "6ikfrX66gYo", title: "🧬How to Get EEVEE?🧬 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "Yu2N5zAtb3o", title: "⚡🔥💧What is the BEST EEVEE EVOLUTION?💧⚡🔥 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "iDcCTSbTpRc", title: "🐦How to GET FLIGHT?🕊️➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "soJbO7_MAes", title: "☕¿Cómo CONSEGUIR el TÉ y ACCEDER a CIUDAD AZAFRÁN?☕➤ Pokémon Rojo Fuego y Verde Hoja #shorts" },
  { id: "_nBy6b90WD8", title: "🦶🏽HITMONLEE or HITMONCHAN👊🏽 WHICH IS BETTER? 👑➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "zzOUN7PcTKk", title: "💲 How to GET A WALLET? 💲 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "JQNbeg618_s", title: "🔋Cómo CONSEGUIR a PORYGON💾 ➤ Pokémon Rojo Fuego y Verde Hoja #shorts" },
  { id: "UdbpMEaaAEw", title: "👻 Cómo DESBLOQUEAR el GHOST👻 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "xENi0RN58sg", title: "🚀How to clear SILPH CO. FAST🚀 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "Y9u4nxIuOag", title: "🦕How to GET LAPRAS🦕 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "XheX4wVMJAg", title: "🧙🏻‍♀️QUICK PASS the SAFFRON CITY GYM🧙🏻‍♀️ ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "CTmxk0nVvcg", title: "🍎How to get SCRAPS🍎 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "3RXXXJYEAtg", title: "💲How to GET AMULET COIN💲 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "Z51jG-jRR4M", title: "🔔How to get the Relief Bell🔔 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "1uATHCIk3wA", title: "🎧Where to get EXP SHARE🎧 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "JUjxGLYnVvg", title: "🎣How to GET the SUPER ROD🎣 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "e7xSIrCNeAw", title: "🐲Where to catch a DRATINI?🐲 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "MKGTAnB9aaU", title: "🐣How to get LUCKY EGG🐣 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "K7q-RoPiw3M", title: "💪How to get STRENGTH💪 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "OaZM5vb6mGM", title: "👑RARE Pokémon from the SAFARI ZONE👑 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "vsZvvj1PBmg", title: "🌊How to get SURF🌊 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "42fZujv1xis", title: "🦕How to Get AERODACTYL and OLD AMBER?💎 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "4DhG7TiWXt0", title: "💨How to get Quick Claw💨 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "RO2XblXwULo", title: "✅INFINITE STEPS TRICK in the SAFARI ZONE ♾️➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "yXv-cahSTdM", title: "🔑How to open the Isla Canela Gym 🔑 Pokémon FireRed and LeafGreen #shorts" },
  { id: "0Vm8nGx6FRQ", title: "🔓How to OPEN the GREEN CITY GYM🟢 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "6ZDIgguDHno", title: "👊 How to get ROCK STRIKE 👊 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "WzwFI862Yxs", title: "📇 Cómo Conseguir la POKÉDEX NACIONAL 📇 ➤ Pokémon Rojo Fuego y Verde Hoja #shorts" },
  { id: "5AwCVRrPk9I", title: "💎 Cómo Conseguir el Rubí y el Iris-Ticket 🌈 ➤ Pokémon Rojo Fuego y Verde Hoja #shorts" },
  { id: "VMmfCwGW38U", title: "💧Cómo conseguir MO07 CASCADA💧 ➤ Pokémon Rojo Fuego y Verde Hoja #shorts" },
  { id: "dzXbrKWpE7g", title: "🥚 How to Get the Togepi Egg 🥚 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "rH6B9V2UU-8", title: "📍How to open Dotted Hole📍 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "E9EYsVoA1j4", title: "💎How to Get the Sapphire💎 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "eovKN1lWLrA", title: "👽How do you enter Cerulean Cave?👽 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "-oJukApS8oo", title: "❓The Secret of Seventh Island❓ ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "tauYLMPCmAI", title: "❄️How to get Articuno❄️ ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "KaVyRAnSfyw", title: "⚡How to get Zapdos⚡ ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "MrP_brvNcsc", title: "🔥How to get Moltres🔥 ➤ Pokémon FireRed and LeafGreen #shorts" },
  { id: "LcGnQ6fG7n4", title: "How to Catch RAIKOU, ENTEI, and SUICUNE ➤ Pokémon FireRed and LeafGreen #shorts" },
];
